### ISSUE TITLE
Show plugin name on hover in toolbox

### ISSUE THREAD

**Issue by goliakshay357** [Canvasbird/canvasboard#61] opened 2020-09-25 17:49 UTC

**Comment by geeks5551** [comment] 2020-10-01 19:50
hey can I contribute to the advanced CSS styling like animation,transition ,translation ,flexbox,media query etc to make the issue more responsive?

**Comment by goliakshay357** [comment] 2020-10-01 21:02
@geeks5551  Sure :+1:

**Comment by goliakshay357** [comment] 2020-10-01 21:02
Curious to know your ideas and pipeline.

**Comment by geeks5551** [comment] 2020-10-01 21:31
ya sure , so can you please assign me this issue

**Comment by goliakshay357** [comment] 2020-10-01 21:33
Sure. 
Can you please join our IRC channel for further discussion? 
Link: https://gitter.im/canvasbird/canvasboard-frontend
Thanks

**Comment by geeks5551** [comment] 2020-10-01 21:36
okk sure will do that

**Comment by geeks5551** [comment] 2020-10-01 21:39
but please assign me with this issue first so that I can start with the work ?

**Comment by kingavatar** [comment] 2020-10-31 19:45
Duplicate of #159

**Closed by kingavatar** 2020-10-31 19:45 UTC
Labels: creative-board, good first issue, hacktoberfest🌈🚀
